export const Candidates=[
    {
        key:1,
        Name:"srinibha srikanth",
        domain:"Social media",
        batch:"2021-25",
        emailid:"srinibha.srikanth@gmail.com",
    },
    {
        key:2,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:3,
        Name:"L.varunesh",
        domain:"Social media",
        batch:"2021-25",
        emailid:"lvarunesh26@gmail.com",
    },
    {
        key:4,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:5,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:6,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:7,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:8,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:9,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:10,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:11,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:12,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:13,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:14,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:15,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:16,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:17,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:18,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:19,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:20,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:21,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:22,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
    {
        key:23,
        Name:"Aashritha Bibireddy",
        domain:"Social Media",
        batch:"2021-25",
        emailid:"aashrithabibireddy@gmail.com",
    },
]